# .travis.yml

language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
      global:
        # Doctr deploy key for griffin-h/superphot
        - secure: "UA+9pHdq/8EjFiYCmThB1Qt1XT2F+Hrph3l8Q1EDIxurIK718txyiL5ihZLR1vEThaYN21zcAemyFOq2mQQzEeP2xzsWaMPDPEs5RjFxLKaG1sD/rmQT7t/qEb+90AXP+h8m/jQLqGqZsUOl2WJIXctnVlXhxua7miGmCWIN47YqRnUpPYejW1CHvjA9nWscz46/pK5q/gULqHh5/h0wuGggODBdGdntwEgmF3295UXpcbse8em42IgkSiyxEGLUM+Rt4QN3CWpH/08dn4eHh5ij/y1OYia8+kUv0N1uQ+FmX9xSlcbWvUQo5o3u7h4ckOqn5suO4J9uTe32PYPak/84WnCb0g5tHNJBvj9xnP6XJuRvayTb20jKaplFebyK1TaiIU0IiUwyPpJLFijS6W6HrcDZYfVWWPAE7XCsqRq5s5heKyYkvKu3ly6zskDVXXgTClsXaTSh8QFIn868xM5RswpNZoyXGlaYXnCvFEQiG0asRkwfi2jLKiOp4eNPAK/8s16tHhX3ozCKYGkUmC753VQyqkeKOh8cTnHJIy/JEr8LouGf8ebUzhp4cS31HtG5TXhxzgrpD6gGgy6aV4VgWQPWInNfT2Yy58IvWsShfgzTdrwwLCBFYYkt5ZICPyI5xfZFP/liMxr70FdGbozqu/bADAlwAKaswt2wGnc="

install:
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - set -e  # If any of the following steps fail, just stop at that point.
  - make -C docs html  # Build the documentation.
  - pip install doctr
  - doctr deploy --built-docs docs/build/html .  # Publish the documentation.
